// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RWM_gaussian_mixture
arma::vec RWM_gaussian_mixture(int n, double x0, double mu1, double mu2, double sigma1, double sigma2, double w1, double w2, double qsigma, double seed);
RcppExport SEXP _code815_RWM_gaussian_mixture(SEXP nSEXP, SEXP x0SEXP, SEXP mu1SEXP, SEXP mu2SEXP, SEXP sigma1SEXP, SEXP sigma2SEXP, SEXP w1SEXP, SEXP w2SEXP, SEXP qsigmaSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type mu1(mu1SEXP);
    Rcpp::traits::input_parameter< double >::type mu2(mu2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type w1(w1SEXP);
    Rcpp::traits::input_parameter< double >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< double >::type qsigma(qsigmaSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(RWM_gaussian_mixture(n, x0, mu1, mu2, sigma1, sigma2, w1, w2, qsigma, seed));
    return rcpp_result_gen;
END_RCPP
}
// RWM_truncated_gaussian_mixture
arma::vec RWM_truncated_gaussian_mixture(int n, double x0, double mu1, double mu2, double sigma1, double sigma2, double w1, double w2, double qsigma, double radius, double seed);
RcppExport SEXP _code815_RWM_truncated_gaussian_mixture(SEXP nSEXP, SEXP x0SEXP, SEXP mu1SEXP, SEXP mu2SEXP, SEXP sigma1SEXP, SEXP sigma2SEXP, SEXP w1SEXP, SEXP w2SEXP, SEXP qsigmaSEXP, SEXP radiusSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type mu1(mu1SEXP);
    Rcpp::traits::input_parameter< double >::type mu2(mu2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type w1(w1SEXP);
    Rcpp::traits::input_parameter< double >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< double >::type qsigma(qsigmaSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(RWM_truncated_gaussian_mixture(n, x0, mu1, mu2, sigma1, sigma2, w1, w2, qsigma, radius, seed));
    return rcpp_result_gen;
END_RCPP
}
// gradient_descent_BB_lsq
Rcpp::List gradient_descent_BB_lsq(const arma::vec& y, const arma::mat& A, const arma::vec& x0, double lambda, double tol, int max_iter, bool printing);
RcppExport SEXP _code815_gradient_descent_BB_lsq(SEXP ySEXP, SEXP ASEXP, SEXP x0SEXP, SEXP lambdaSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP printingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type printing(printingSEXP);
    rcpp_result_gen = Rcpp::wrap(gradient_descent_BB_lsq(y, A, x0, lambda, tol, max_iter, printing));
    return rcpp_result_gen;
END_RCPP
}
// irls_poisson
arma::vec irls_poisson(const arma::vec& y, const arma::mat& X, const arma::vec& beta0, double tol, int max_iter, bool printing);
RcppExport SEXP _code815_irls_poisson(SEXP ySEXP, SEXP XSEXP, SEXP beta0SEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP printingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type printing(printingSEXP);
    rcpp_result_gen = Rcpp::wrap(irls_poisson(y, X, beta0, tol, max_iter, printing));
    return rcpp_result_gen;
END_RCPP
}
// loss_ridge
double loss_ridge(const arma::vec& y, const arma::mat& A, const arma::vec& x, double lambda);
RcppExport SEXP _code815_loss_ridge(SEXP ySEXP, SEXP ASEXP, SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(loss_ridge(y, A, x, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_code815_RWM_gaussian_mixture", (DL_FUNC) &_code815_RWM_gaussian_mixture, 10},
    {"_code815_RWM_truncated_gaussian_mixture", (DL_FUNC) &_code815_RWM_truncated_gaussian_mixture, 11},
    {"_code815_gradient_descent_BB_lsq", (DL_FUNC) &_code815_gradient_descent_BB_lsq, 7},
    {"_code815_irls_poisson", (DL_FUNC) &_code815_irls_poisson, 6},
    {"_code815_loss_ridge", (DL_FUNC) &_code815_loss_ridge, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_code815(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
