# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

irls_poisson <- function(y, X, beta0, tol = 0.0001, max_iter = 10000L, printing = FALSE) {
    .Call(`_code815_irls_poisson`, y, X, beta0, tol, max_iter, printing)
}

loss_ridge <- function(y, A, x, lambda) {
    .Call(`_code815_loss_ridge`, y, A, x, lambda)
}

